version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.backend
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=postgresql://tax_user:tax_password@postgres:5432/tax_intelligence
      - REDIS_URL=redis://redis:6379/0
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    depends_on:
      - postgres
      - redis
    volumes:
      - ../../backend:/app/backend
      - ../../knowledge_base:/app/knowledge_base
    networks:
      - tax-intelligence

  # Frontend
  frontend:
    build:
      context: ../..
      dockerfile: deployments/docker/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:5000
    volumes:
      - ../../frontend/src:/app/src
      - ../../frontend/public:/app/public
    networks:
      - tax-intelligence

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=tax_intelligence
      - POSTGRES_USER=tax_user
      - POSTGRES_PASSWORD=tax_password
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    networks:
      - tax-intelligence

  # Redis Cache
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - tax-intelligence

  # Nginx Reverse Proxy (Production)
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - backend
      - frontend
    networks:
      - tax-intelligence
    profiles:
      - production

volumes:
  postgres_data:
  redis_data:

networks:
  tax-intelligence:
    driver: bridge
